### PR TITLE
Added=>Algorithms => Check_Prime => Segmented_Sieve=> Segmented_Sieve.java

### PR DESCRIPTION
**Pull request by GarvitBanga**
Added=>Algorithms => Check_Prime => Segmented_Sieve=> Segmented_Sieve.java

## Assigned Issue Number ?
#1058

## Language Opted ?
Java

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Check_Prime => Segmented_Sieve=> Segmented_Sieve.java

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @GarvitBanga :wave: 
Kindly push the program file into the correct directory
Maths_And_Stats => Number_Theory => Segmented_Sieve
:v:

**Review by Mr-Vaibhav-Shukla — APPROVED** [review]

**Review by Mr-Vaibhav-Shukla — CHANGES_REQUESTED** [review]
Hi @GarvitBanga wave
Kindly push the program file into the correct directory
Maths_And_Stats => Number_Theory => Segmented_Sieve :v:

**Comment by GarvitBanga** [comment]
I have created a new pull request Added Maths_And_Stats => Number_Theory => Segmented_Sieve=> Segmented_Sieve.java #1165. Please review @Mr-Vaibhav-Shukla

**Comment by ahampriyanshu** [comment]
You could have rectified  this one :v:

**Pull request closed without merging**
