### PR TITLE
Added Compound_Interest folder + (cpp, js) solutions

### PR DESCRIPTION
**Pull request by uV3301**
## Assigned Issue Number ?
#763 

## Language Opted ?
C++, JS, python

## Number of files added or updated ?
2

## Name of these files ?
Maths_And_Stats => Statistics => Compound_Interest => Compound_Interest.cpp
Maths_And_Stats => Statistics => Compound_Interest => Compound_Interest.js
Maths_And_Stats => Statistics => Compound_Interest => Compound_Interest.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by uV3301** [comment]
Update: Created python solution.

**Review by ahampriyanshu — APPROVED** [review]
Perfect code :+1: 
Thanks @uV3301     
Happy contributing :v:

**Comment by uV3301** [comment]
Happy to share and learn! @ahampriyanshu

**Comment by ahampriyanshu** [comment]
My pleasure @ahampriyanshu

**Comment by ahampriyanshu** [comment]
My pleasure @uV3301 :v:

**Pull request merged**
