### PR TITLE
Sbhavya18 patch 1

### PR DESCRIPTION
**Pull request by sbhavya18**
## Assigned Issue Number ?
#101 

## Language Opted ?
C++
## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Sort_Algorithm => Bitonic_sort.cpp 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by sbhavya18** [comment]
please forgive me if i made mistakes. This is my first ever pull request.

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code 👏🏽 👏🏽 
Thanks @sbhavya18 
Happy Contributing 🎉

**Comment by ahampriyanshu** [comment]
Major merge conflits ⚠️ 
Hi @sbhavya18, Please do not push README file

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Kindly remove the README.md file from your pull request

**Pull request closed without merging**
