### PR TITLE
Ahampriyanshu

### PR DESCRIPTION
**Pull request by deepanshuoct12**
## Assigned Issue Number ?
#686

## Language Opted ?
C++

## Number of files added or updated ?
1

## Name of these files ?
Algo=>Added=>Dynamicprogramming=>LIS=>Cpp

### Checklist
- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @deepanshuoct12 :wave: ,
Please sync up your forked repo and then look for pre-existing files.
And also don't edit any **.md** and **.yml** files.
:v:

**Comment by deepanshuoct12** [comment]
I have committed changes now can u please take a look at it and merge?

**Comment by ahampriyanshu** [comment]
> I have committed changes now can u please take a look at it and merge?

No you didn't. :warning: 
You are still editing the main README of the repo.

**Comment by deepanshuoct12** [comment]
I have committed changes now can u please take a look at it and merge?please

**Pull request closed without merging**
