### PR TITLE
adding factorial in swift

### PR DESCRIPTION
**Pull request by rgarg-2711**
## Assigned Issue Number ?#1027
#007

## Language Opted ?swift
C/C++/Python/Java/...

## Number of files added or updated ?1
1/2/3/4/...

## Name of these files ?Maths_And_Stats => Algebra => Factorial => Factorial.swift
main folder => sub_folder => ... => ... => ... file.py

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by rgarg-2711** [comment]
in reference to issue #1027 thank you for assign me.

**Review by ahampriyanshu — APPROVED** [review]
Hi @rgarg-2711 :wave: ,
Please push complete program that takes the input dynamically.
:v:

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Also fill the PR template properly.

**Comment by rgarg-2711** [comment]
in reference to issue #1027 update the solution

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @rgarg-2711 
Happy Contributing :tada:

**Comment by rgarg-2711** [comment]
thank you for merging.

**Pull request merged**
