### PR TITLE
Bubble Sort added for JavaScript

### PR DESCRIPTION
**Pull request by Harshi7016**
@ahampriyanshu  I usually do this in leetcode and get the result.
Please let me know if this is good or shall I explore more on how to create a web page to display results. 
Thank You.

### CODE REVIEW

**Review by ahampriyanshu — APPROVED** [review]
LGTM
Thanks @Harshi7016

**Comment by Harshi7016** [comment]
Awesome 👍

**Comment by Harshi7016** [comment]
In that case , Can I take up another issue?

**Comment by ahampriyanshu** [comment]
Sure , go ahead
BTW if you want you can create a new issue

**Pull request merged**
