### PR TITLE
#78 implementation of maps 

### PR DESCRIPTION
**Pull request by anshupatel06**
## Assigned Issue
#78 

### Have you read the [Contributing Guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/master/CONTRIBUTING.md)?
Yes/No

### Files Affected ?
map.cpp

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by anshupatel06** [comment]
please assign it to me

**Review by ahampriyanshu — APPROVED** [review]
LGTM 👍🏽 
thanks @anshupatel06

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
@anshupatel06 Please mention the issue number

**Comment by anshupatel06** [comment]
i added the issue number

**Comment by anshupatel06** [comment]
i mention the issue number please merge it

**Comment by anshupatel06** [comment]
please accept it as hacktoberfest accepted

**Pull request merged**
