### PR TITLE
LCA|Python

### PR DESCRIPTION
**Pull request by aroradhruv2308**
## Assigned Issue Number ?
#1327 

## Language Opted ?
Python

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Tree_Algorithms => LCA => LCA.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @aroradhruv2308 ,
Please push the complete program.
:v:

**Review by Dheeraj-01 — APPROVED** [review]

**Comment by aroradhruv2308** [comment]
@ahampriyanshu Done

**Comment by aroradhruv2308** [comment]
@ahampriyanshu I have made another PR of updated code. Should I close this PR?

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @aroradhruv2308 
Happy Contributing :tada:

**Pull request merged**
