### PR TITLE
added group_anagrans.js

### PR DESCRIPTION
**Pull request by Kadermiyanyedi**
## Assigned Issue Number ?
#1368 
## Language Opted ?
Javascript

## Number of files added or updated ?
1

## Name of these files ?
Data_Structures => Maps_Hash_Dict => Group_Anagrams => group_anagrams.js

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've referred the correct issue number.
- [x ] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @Kadermiyanyedi ,
Please take the user's input dynamically.

**Comment by Kadermiyanyedi** [comment]
@ahampriyanshu I changed my code, can you control it?

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu I changed my code, can you control it?

What do you mean by ``control it`` ?
Kindly explain.
:v:

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @Kadermiyanyedi 
Happy Contributing :tada:

**Pull request merged**
