### PR TITLE
Added Maths_And_Stats =>Algebra=> Babylonian=>Babylonian.cpp

### PR DESCRIPTION
**Pull request by demonslayer99**
## Assigned Issue Number ?
#1374

## Language Opted 
C++

## Number of files added 
1

## Name of these files 
Maths_And_Stats =>Algebra=> Babylonian=>Babylonian.cpp

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by demonslayer99** [comment]
@ahampriyanshu why is kasai algo getting committed in the Babylonian algo.? what am I doing wrong?

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @demonslayer99 ,
Please take the user's input dynamically.

**Comment by demonslayer99** [comment]
done

**Comment by demonslayer99** [comment]
HELP!

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu why is kasai algo getting committed in the Babylonian algo.? what am I doing wrong?


> HELP! @ahampriyanshu

Well to be frank, there nothing wrong with this PR.
But you have added a lot of unnecessary commits while making this PR :warning:

So, do the following

- Delete this branch
- Sync up your repository
- Again create a new branch
- Commit the new file to that branch
- Create a PR

PS: **Do not unnessarily create or delete any random file in your branch when you know you are going to create a PR for a new specific file.**

**Comment by ahampriyanshu** [comment]
And also do not directly commit on master branch.

**Pull request closed without merging**
