### PR TITLE
Added Readme 

### PR DESCRIPTION
**Pull request by monishamandal02**
## Assigned Issue Number ?
#007

## Language Opted ?
C/C++/Python/Java/...

## Number of files added or updated ?
1/2/3/4/...

## Name of these files ?
main folder => sub_folder => ... => ... => ... file.py

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [ ] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by monishamandal02** [comment]
Please Check my Readme file of Sorting as well.   :)

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Thanks @monishamandal02
Please add the worst and best time complexity for each :v:

**Comment by monishamandal02** [comment]
Okk sure I will add.

**Comment by ahampriyanshu** [comment]
I will add them later myself :grin: 
Thanks for contributing :v: 
Can you to do that for other folders too :question:

**Comment by monishamandal02** [comment]
ok

**Comment by ahampriyanshu** [comment]
Great :+1: 
I am creating a new ``documentation`` issue
Refer to that issue number while creating the PRs
Thanks again :v:

**Comment by ahampriyanshu** [comment]
Well :sweat_smile: 
I am not creating any new issue related to ducumentation.
That will recieve a lot of spam/invalid/incomplete PRs from folks who just want to win a T-Shirt without doing much(thanks to shitoberfest)
Kindly keep #65 while creating the PR and please follow at the above instead of the actual one.(You have to fill just a single Line)
:v:

**Comment by monishamandal02** [comment]
alright :)

**Comment by monishamandal02** [comment]
I created a new pull request with #65. I hope I had followed the guideline properly. I will be adding rest of the readme files soon.   :)

**Comment by ahampriyanshu** [comment]
Don't fill whole PR template.


## Documentation No ?
#65 

## Folder/subfolder documented?
Algorithm => Sorting_Algorithm


You can use this template instead.

**Comment by ahampriyanshu** [comment]
Don't fill the whole PR template.


## Issue No ?
#65 

## Folder/Subfolder Documented?
Algorithm => Sorting_Algorithm


You can use this template instead.

**Pull request merged**
