### PR TITLE
Added main folder => Maths_And_Stats => Series => Sum_Of_AP.py

### PR DESCRIPTION
**Pull request by SayaniG371**
## Assigned Issue Number ?
#306 

## Language Opted ?
Python

## Number of files added or updated ?
1 File Added

## Name of these files ?
main folder => Maths_And_Stats => Series => Sum_Of_AP.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by SayaniG371** [comment]
Can I get some help ?  The first is failing( Welcome / run (pull_request) ).
@ahampriyanshu

**Comment by SayaniG371** [comment]
@ahampriyanshu Please review this PR

**Comment by SayaniG371** [comment]
@ahampriyanshu  @Vimlesh-Kumar  Please review my PR, all checks have been passed

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @SayaniG371 
Happy Contributing :clap:

**Comment by SayaniG371** [comment]
Thank you !

**Pull request merged**
