### PR TITLE
Algorithms => String_Algorithms => LPS => longest_palindromic_substring.java

### PR DESCRIPTION
**Pull request by harshitashankar**
## Assigned Issue Number ?
#1337 

## Language Opted ?
Java

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => String_Algorithms => LPS => longest_palindromic_substring.java

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by harshitashankar** [comment]
@ahampriyanshu Please review.

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @harshitashankar ,
Please take the user's input dynamically.

**Comment by harshitashankar** [comment]
@ahampriyanshu  Updated.

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @harshitashankar 
Happy Contributing :tada:

**Pull request merged**
