### PR TITLE
Added => Algorithms => Search_Algorithms => Binary_Search => Rotated-…

### PR DESCRIPTION
**Pull request by mandloiaditi**
…Sorted-Array-Search.js

## Assigned Issue Number ?
#1217 

## Language Opted ?
Javascript

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Search_Algorithms => Binary_Search => Rotated-Sorted-Array-Search.js

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @mandloiaditi ,
Please take the user's input dynamically.

**Comment by mandloiaditi** [comment]
please have a look at the changes as requested @ahampriyanshu . Also I would want to learn this thing, is it advisable to re base with upstream every time we make changes to an existing pull request or it should not be done ?

**Comment by ahampriyanshu** [comment]
> please have a look at the changes as suggested @ahampriyanshu . Also I would want to learn this thing, is it advisable to re base with upstream every time we make changes to an existing pull request or it should not be done ?

No, you should always try to avoid rebasing whenever you are updating some specific files with no merge conflicts(like in this case).
Just commit the changes to that/those file/files.

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @mandloiaditi  
Happy Contributing :tada:

**Pull request merged**
