### PR TITLE
LCM for n numbers using Javascript

### PR DESCRIPTION
**Pull request by yogeswarl**
## Assigned Issue Number ?
#301 

## Language Opted ?
Javascript

## Number of files added or updated ?
1 file added

## Name of these files ?
Maths_And_Stats => Algebra => LCM =>  LCM.js

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @yogeswarl , please take the input dynamically,
See the **contributing guidelines**

**Comment by yogeswarl** [comment]
Sure I will work on it.

**Comment by yogeswarl** [comment]
> Sure I will work on it.

I have made the changes for a dynamic input

**Comment by yogeswarl** [comment]
Hey, I have made the change to bring it as dynamic input, I don't understand why my request was not merged

**Pull request closed without merging**
