### PR TITLE
stack using array in go

### PR DESCRIPTION
**Pull request by harshitsuthar77731**
## assigned issue no. 
#1608

##Language opted
#go

##number of file added or updated
#1

## Assigned Issue Number ?
#Issue_Number

## Language(s) Opted ?
C/C++/Python/Java ...

## Number of file(s) added or updated ?
1/2/3/4/...

## Name and location of the file(s) ?
Folder => Sub_Folder => ... => File.extension

### Checklist

- [X] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [X] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [X] Input has been taken dynamically.
- [X] I've referred the correct issue number.
- [X] Comments have been added
- [X] I've  synced-up my forked repo.
- [X] Ain't pushing from the main branch.

### CODE REVIEW

**Review by ahampriyanshu — COMMENTED** [review]
don't use camel case => https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md#naming-convention

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @harshitsuthar77731, please follow naming convention

**Comment by harshitsuthar77731** [comment]
updated name according to naming convention

**Comment by harshitsuthar77731** [comment]
i have updated the naming convention kindly merge it

**Comment by harshitsuthar77731** [comment]
merge this  code and add hactober fest tag happy coding

**Comment by harshitsuthar77731** [comment]
@ahampriyanshu

**Review by ahampriyanshu — COMMENTED** [review]
Thanks @harshitsuthar77731,
Happy Contributing :tada:

**Comment by harshitsuthar77731** [comment]
please add hactoberfest tag

**Comment by harshitsuthar77731** [comment]
and why it's showing ❌ tag help me about this issue

**Pull request merged**
