### PR TITLE
Search in a sorted 2-D matrix (BINARY SEARCH) (#1689) java added

### PR DESCRIPTION
**Pull request by raazanand**
## Location of the file(s) ?
Algorithm =>Searching =>Binary Search=>search_in_2D_matrix.java

**Kindly review my PR #1689**

### Checklist

- [x] I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [x] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [x] Input has been taken dynamically.
- [x] I've referred the correct issue number.
- [x] Comments have been added
- [x] I've  synced-up my forked repo.
- [x] Ain't pushing from the main branch.

### CODE REVIEW

**Comment by raazanand** [comment]
Stack Using Linked List done! Kindly review my PR #1609

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @raazanand , please take the input dynamically.

**Review by raazanand — COMMENTED** [review]
Update: Input taken dynamically

**Comment by raazanand** [comment]
@ahampriyanshu changes done accordingly.Please review the same

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu changes done accordingly.Please review the same

Do the same for ``StackUsingLL.java``.

**Review by raazanand — COMMENTED** [review]
Dynamic input support added for both programs

**Comment by raazanand** [comment]
> > @ahampriyanshu changes done accordingly.Please review the same
> 
> Do the same for `StackUsingLL.java`.

@ahampriyanshu done!

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1:
Thanks @raazanand 
Happy Contributing :tada:

**Pull request merged**
