### PR TITLE
 add-selection_sort.c-program

### PR DESCRIPTION
**Pull request by SUJATA19-could**
## Assigned Issue Number ?
#415 

## Language Opted ?
C

## Number of files added or updated ?
1/2/3/4/...

## Name of these files ?
main folder => sub_folder => ... => ... => ... file.py

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Comment by SUJATA19-could** [comment]
done!

**Comment by SUJATA19-could** [comment]
hey! merge it

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @SUJATA19-could  
Happy Contributing :clap:

**Comment by SUJATA19-could** [comment]
My pleasure🙂

**Pull request merged**
