### PR TITLE
longest common subsequence of two sequences in python

### PR DESCRIPTION
**Pull request by SoundaryaKhanapur**
## Assigned Issue
#113 #89 

### Have you read the [Contributing Guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/master/CONTRIBUTING.md)?
Yes

### Files Affected ?
Longest Common Subsequence of Two Sequences.py, Selection Sort.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @SoundaryaKhanapur , please remove all the unnecessary files.

**Comment by SoundaryaKhanapur** [comment]
Yes, working on it now

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code 👏🏽
Thanks @SoundaryaKhanapur 
Happy Contributing 🎉

**Comment by SoundaryaKhanapur** [comment]
Thank you @ahampriyanshu
Happy to contribute 🙌🏻

**Pull request merged**
