### PR TITLE
Added => Algorithms => Dynamic_Programming => Count_Square_Matrices.py

### PR DESCRIPTION
**Pull request by g-jindal2001**
## Assigned Issue Number ?
#1160 

## Language Opted ?
Python

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Dynamic_Programming => Count_Square_Matrices.py

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @g-jindal2001 :wave:,
Please take the input dynamically.
:v:

**Comment by g-jindal2001** [comment]
@ahampriyanshu Will do it

**Comment by g-jindal2001** [comment]
@ahampriyanshu  Please review the changes

**Review by g-jindal2001 — COMMENTED** [review]
I have updated code for user input

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @g-jindal2001 
Happy Contributing :tada:

**Pull request merged**
