### PR TITLE
Guilherme oliveira casagrande

### PR DESCRIPTION
**Pull request by GuilhermeOliveiraCasagrande**
## Assigned Issue Number ?
#1353

## Language Opted ?
TypeScript

## Number of files added or updated ?
1

## Name of these files ?
Algorithms => Sorting_Algorithms => strand_sort.ts

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @GuilhermeOliveiraCasagrande ,
Please take the user's input dynamically.

**Comment by GuilhermeOliveiraCasagrande** [comment]
@ahampriyanshu do you mean to take the input from the console? Or the  code I send be just the function?

**Comment by ahampriyanshu** [comment]
> @ahampriyanshu do you mean to take the input from the console? Or the function must accept any type?

Take input from the console.

**Comment by GuilhermeOliveiraCasagrande** [comment]
I would have to create files that aren't relate do algorithms at all and pollute the project just to have TypeScript to get user input, are you sure about that?

**Comment by ahampriyanshu** [comment]
> I would have to create files that aren't related do algorithms at all and pollute the project just to have TypeScript to get user input, are you sure about that?

Understood

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @GuilhermeOliveiraCasagrande
Happy Contributing :tada:

**Pull request merged**
