### PR TITLE
C++ program calculates the mean of numbers the user inputs

### PR DESCRIPTION
**Pull request by js899**
## Assigned Issue ?
#159 

## Language Opted ?
C++

## Number of files added or updated ?
1

## Name of these files ?
mean.cpp

example :
algo_ds_101 => Maths_And_Stats => mean.cpp
Maths_And_Stats/mean.cpp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @js899 , please fill up the PR template correctly.

**Comment by js899** [comment]
@ahampriyanshu I didn't get what you're asking about the PR template can you please elaborate I'm new to open sourcing

**Comment by js899** [comment]
I mistakenly closed it, I reopened it.

**Review by ahampriyanshu — APPROVED** [review]
Perfect 👏🏽
thanks @js899 ,
Happy Contributing 🎉

**Comment by js899** [comment]
thanks @ahampriyanshu

**Comment by js899** [comment]
> Perfect 👏🏽
> thanks @js899 ,
> Happy Contributing

Hi, could you please add the label "hacktoberfest-accepted" to my PR, thanks.

**Comment by js899** [comment]
> > Perfect 👏🏽
> > thanks @js899 ,
> > Happy Contributing
> 
> Hi @ahampriyanshu , could you please add the label "hacktoberfest-accepted" to my PR, thanks.

**Pull request merged**
