### PR TITLE
Added =>Maths_And_Stats=>Statistics=>Standard_Deviation

### PR DESCRIPTION
**Pull request by cuber485**
added Standard_Deviation in C

## Assigned Issue Number ?
#177 #214 

## Language Opted ?
C and Java

## Number of files added or updated ?
2

## Name of these files ?
Maths_And_Stats=> Statistics=> Standard_Deviation=> Standard_Deviation.c

example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by sakshamsablok — COMMENTED** [review]
Hey,
It would be good if you push changes or commit changes with respect to Issue id. 
For instance, here you pushed knapsackProblem changes in Standard_Deviation Issue(issue id #177 ).

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code 👏🏽
Thanks @cuber485 
Happy Contributing :tada:

**Comment by cuber485** [comment]
@sakshamsablok Thanks for help.

**Comment by cuber485** [comment]
@ahampriyanshu  Happy to contribute.

**Pull request merged**
