### PR TITLE
Added => Data Structures => Tree => Binary_Tree => Right_View => right_view_of_binary_tree.cpp

### PR DESCRIPTION
**Pull request by sanjiti0606**
## Assigned Issue Number ?
#1247 

## Language Opted ?
C++

## Number of files added or updated ?
1

## Name of these files ?
algo_ds_101 => Data Structures => Tree => Binary_Tree => Right_View => right_view_of_binary_tree.cpp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @sanjiti0606 :wave:,
Please push the complete program,  which takes the input dynamically.

**Comment by sanjiti0606** [comment]
WhatsApp Image 2020-10-10 at 23 48 57
Hi, @ahampriyanshu just wanted to clarify do you mean like this, ie. taking an example tree?
(This is a PR you've accepted)

**Comment by sanjiti0606** [comment]
I've made changes, @ahampriyanshu please review. Thanks.

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @sanjiti0606 
Happy Contributing :tada:

**Pull request merged**
