### PR TITLE
K-means_Clustering

### PR DESCRIPTION
**Pull request by Mrsterius**
## Assigned Issue Number ?
#764 

## Language Opted ?
Python

## Number of files added or updated ?
1

## Name of these files ?
Maths_And_Stats => Statistics => K-means_Clustering => K-means_Clustering.py

example :
Sklearn's make blobs dataset => K_means_Algorithm => Resultant clusters => K-means_Clustering.py

### Checklist

- [y] I've read the contribution guidelines.
- [y] I've referred the correct issue number.
- [y] I've fill up this entire template correctly.

### CODE REVIEW

**Review by ahampriyanshu — CHANGES_REQUESTED** [review]
Hi @Mrsterius :wave: 
Please remove your .DS conf file
:v:

**Comment by Mrsterius** [comment]
Hi Priyanshu,

I am new with this. Should I make a new pull request or if you could guide me to remake changes here.

**Comment by ahampriyanshu** [comment]
No,  you don't need to create another new PR.
Just delete those files in your forked repo then pull again to my master branch
:v:

**Comment by Mrsterius** [comment]
I have deleted the .DS files and made the commit showing one final file. However, I don't see an option to pull again when I go to pull requests. Please guide for the same.

**Comment by Mrsterius** [comment]
On reading about it, I found that Github updates the changes automatically. Thanks.

> I have deleted the .DS files and made the commit showing one final file. However, I don't see an option to pull again when I go to pull requests. Please guide for the same.

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @Mrsterius 
Happy Contributing :tada:

**Pull request merged**
