### PR TITLE
added double hashing algorithm; closes #1666

### LINKED ISSUE #1666: Open Addressing (Hashing) using Double Hashing
### Type

Algorithm

### Directory

Algorithm => Hashing => Open-Addressing => DoubleHashHashingTable.cpp

### Description

**Double hashing** is a collision resolving technique in Open Addressed Hash tables. Double hashing uses the idea of applying a second hash function to key when a collision occurs.
```txt
Double hashing can be done using :
(hash1(key) + i * hash2(key)) % TABLE_SIZE
Here hash1() and hash2() are hash functions and TABLE_SIZE
is size of hash table.
(We repeat by increasing i when collision occurs)
```

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

### PR DESCRIPTION
**Pull request by iamHrithikRaj**
## Assigned Issue Number ?
#1666

## Language(s) Opted ?
C++

## Number of file(s) added or updated ?
1

## Name and location of the file(s) ?
Algorithm => Hashing => Open Addressing => doubleHashHashingTable.cpp

### Checklist

- [X] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [X] I've synced-up my forked repo.
- [X] Ain't pushing from the main branch.
- [X] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [X] Input has been taken dynamically.
- [X] I've referred the correct issue number.
- [X] Comments have been added
- [X] I've  synced-up my forked repo.
- [X] Ain't pushing from the main branch.

### CODE REVIEW

**Review by ahampriyanshu — APPROVED** [review]
Perfect Code :+1: 
Thanks @iamHrithikRaj 
Happy Contributing :tada:

**Comment by Sun-0321** [comment]
Isn't it necessary to add hacktober_accepted label to be processed by hacktober??

If so,kindly do it.

**Comment by Sun-0321** [comment]
> 
> 
> Perfect Code 👍 Thanks @iamHrithikRaj Happy Contributing 🎉
Isn't it necessary to add hacktober_accepted label to be processed by hacktober??

If so,kindly do it.

**Comment by iamHrithikRaj** [comment]
@ahampriyanshu the PRs are not marked as `hacktoberfest-accepted`. Please look into this.

Regards

**Pull request merged**
